using System;
using UnityEngine;

namespace PokeMemories.Gameplay
{
    /// <summary>
    /// Sprites for the track items and the three parallax background sets.
    /// Filled by the editor menu PokeMemories > Build Track Art Set from Assets/Art/Track and
    /// Assets/Art/Backgrounds (both generated by tools/sprites/trackart.mjs).
    /// </summary>
    [CreateAssetMenu(menuName = "PokeMemories/Track Art Set")]
    public class TrackArtSet : ScriptableObject
    {
        [Serializable]
        public class BackgroundSet
        {
            public string name;
            public Sprite sky, far, mid, near;
            [Tooltip("Multiplied onto the ground tile while this section is on screen.")]
            public Color groundTint = Color.white;
        }

        public Sprite ball, cone, barrier, kicker, gap, railBar, railPost, step, ground;
        [Tooltip("One set per course section, in order: Rose Walk, Boardwalk Rush, Golden Hour.")]
        public BackgroundSet[] backgrounds = new BackgroundSet[3];
    }
}
